### ISSUE TITLE
Minor edits to the api examples

### ISSUE THREAD

**Issue by scottdchristian** [18F/e-manifest#115]
I moved validating to top, as I want people to use that API at least in 2016 and 2017.  Also added a table of contents in what I assume is the correct format.  small word changes as well
[index.html.zip](https://github.com/18F/e-manifest/files/105604/index.html.zip)

**Comment by scottdchristian** [comment]
Swapped the token and signatures order for flow purposes.  In order for a user to sign a manifest the user must first authenticate (get the token), so I placed token before signature.  Also consistent with the API Examples page
[swagger.zip](https://github.com/18F/e-manifest/files/106580/swagger.zip)

**Comment by pkarman** [comment]
@scottdchristian is this ticket still live? Or did you solve it via github editor?

**Comment by scottdchristian** [comment]
This one is still live, GitHub editor would not let me edit those files.

Thanks,
Scott
On Jan 29, 2016, at 5:19 PM, Peter Karman <notifications@github.com<mailto:notifications@github.com>> wrote:

@scottdchristianhttps://github.com/scottdchristian is this ticket still live? Or did you solve it via github editor?

##

**Comment by pkarman** [comment]
@scottdchristian I have added these edits as best I could to the open PR for API docs #136 

Please review that PR and comment where there still need to be changes.

**Comment by brandocalrissian** [comment]
The PR #136 was closed almost a week ago. Is this still an active issue, @scottdchristian?

**Comment by scottdchristian** [comment]
Thank you for following up, you are correct it's closed.
