### ISSUE TITLE
The <title> on the API documentation says "Swagger UI"

### ISSUE THREAD

**Issue by mbesto** [18F/e-manifest#138]
When you go to:
https://e-manifest.18f.gov/api-documentation/

You see the following in the `<head>` tag:
`<title>Swagger UI</title>`

Looks like it's generated based on the default of this template file:
https://github.com/18F/e-manifest/blob/master/app/views/api-docs/swagger/index.html.erb

I'm not totally familiar with Swagger so I'm not sure how you override the <title> details.

**Comment by brandocalrissian** [comment]
Thanks! We've fixed it in our big conversion to rails. You can catch the different title (E-manifest-rails) in the development environment here: https://e-manifest-dev.18f.gov/api-documentation/

When we push to https://e-manifest.18f.gov, we'll clean up the title further to clarify the purpose of the page, something like "EPA e-Manifest API".

**Comment by brandocalrissian** [comment]
The titles on the site's pages now say "e-Manifest".
