### ISSUE TITLE
Form tasks

### ISSUE THREAD

**Issue by vz3** [18F/e-manifest#2]
- [ ] All grey outlined boxes should have a light gray background #E4E2E0
- [x] 9a should only show up when "There are non-hazardous materials present in this shipment" is selected. If "This shipment is only hazardous material" is selected, hide"
- [ ] FontAwesome circle plus glyph should be added next to any "Add" panels.
- [ ] Grey boxes should be 5 columns
- [ ] Discrepancy grey box should only be shown when discrepancy is checked

**Comment by vz3** [comment]
- [x] If "Generator address different from mailing address" selected, new contact input form should appear.
- [ ] if partial or full rejection selected, should ask for another manifest #.

**Comment by jeremiak** [comment]
Is this still a valuable issue to keep around? Or can we close it and create new trello cards as we have changes we want to make?

cc @zacharycohn

**Comment by zacharycohn** [comment]
Lets close it!
