### ISSUE TITLE
Change request for instructions

### ISSUE THREAD

**Issue by bbingCGI** [18F/e-manifest#57]
I followed the instructions and got everything up and running.  (Thank you for the details!)  While doing so, I wrote down some comments and suggestions.

1) Could you move step 12 (Edit the environment-specific variables ) before step 8 (Run `bundle install`)?

I found that steps 8-forward needed configuration changes before they would work.

2) Could you mention in step 12 to also verify sidekiq.yml configuration is good?

I found that I needed to create /tmp/pid directories (or change the configuration to a different directory).

3) Is foreman and sidekiq in the bundle?

I had to add these manually.

4) When running with `foreman`, my port was 9000.  When running with `rails`, my port was 3000.

Also for a clean installation of Ubuntu, I needed to run this after step 7:

`sudo apt-get install libpq-dev build-essential`

...due to "failed to install pg -v 0.18.4" in the logs.

**Comment by jessieay** [comment]
Thanks for opening this issue, @benjaminBinghamCGI ! I think I've addressed most of these issues in https://github.com/18F/e-manifest/pull/59

**Comment by brandocalrissian** [comment]
tmp/pids creation is fixed in https://github.com/18F/e-manifest/pull/61

**Comment by bbingCGI** [comment]
According to https://github.com/ddollar/foreman/blob/master/README.md ...

> Ruby users should take care _not_ to install foreman in their project's `Gemfile`.

My apologies for that suggestion.

**Comment by jessieay** [comment]
@benjaminBinghamCGI yes, that is the case when it is used locally (foreman not included in Gemfile). 

On another project we used foreman in prod, though, for running multiple services. Wondering if @pkarman knows if that is the plan for e-manifest...

**Comment by pkarman** [comment]
in production we will likely start with foreman and then as we scale, move to separate instances for web and worker, so won't need foreman.

**Comment by pkarman** [comment]
just to clarify: foreman is required for web+worker support in dev, at least. I am not sure why foreman should/should not be in the Gemfile. It is required in any case.

**Comment by jessieay** [comment]
@pkarman reasoning for not including in Gemfile: https://github.com/ddollar/foreman/pull/437#issuecomment-41110407

I will remove from ours if we aren't going to use it in prod. Will add gem installation to setup script, though. Setting up the code on my home computer now so I'm getting good info on what about our setup process is difficult

**Comment by bbingCGI** [comment]
Looks good!
