### ISSUE TITLE
Development state header bar must be on top level site

### ISSUE THREAD

**Issue by NoahKunin** [18F/e-manifest#7]
I thought I had already made an issue for this, but maybe I dreamt it up?

The actual manifest submission mock at https://e-manifest.18f.gov/web has the top level header explaining that we're in `discovery` and what that means, but https://e-manifest.18f.gov does not have that bar. Just need to port it over. Ideally, we do this very quickly, as I'm about to approve the blog post. :D 

Looking at commits, this might be a @brandocalrissian task, but please feel free to re-assign as the project teams sees fit and in concurrence with your sprint schedule.

**Comment by NoahKunin** [comment]
Upon consulting Trello board, @vz3 may need visibility on this one as well.

**Comment by brandocalrissian** [comment]
Agreed on the banner. Working on it now.

**Comment by brandocalrissian** [comment]
Haven't decided yet if it's easier to add the banner to the rest of the site or to change the rest of the site to use https://github.com/18F/web-design-standards . The latter would be preferable given enough time and priority.

**Comment by zacharycohn** [comment]
i'd just add the banner for now.

**Comment by NoahKunin** [comment]
+1 to just banner

**Comment by brandocalrissian** [comment]
We are live.

**Comment by NoahKunin** [comment]
Sweet. I've unblocked the blog post!

On Wed, Nov 25, 2015 at 12:42 PM, Brandon Kirby notifications@github.com
wrote:

> We are live.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/e-manifest/issues/7#issuecomment-159727205.

## 

Noah Kunin
18F Infrastructure Director | @18F https://twitter.com/18F
