### ISSUE TITLE
New requirements for database migration

### ISSUE THREAD

**Issue by bbingCGI** [18F/e-manifest#74]
When updating to the latest, I ran into two problems.
1) Postgres 9.4 or higher is required for jsonb data type.  (Ubuntu 14.04 comes with 9.3)
2) rake db:migrate requires a user with permission to create extensions  (such as postgres user)

Both were easy to overcome.  But thought it was important to note.

**Comment by brandocalrissian** [comment]
We need to document the postgres requirement and create the role in our setup script.

**Comment by brandocalrissian** [comment]
Something like `createuser -s -r postgres`

**Comment by pkarman** [comment]
just discovered cloud.gov uses 9.3 also, so the `jsonb` feature is going to need to be re-thought in any case.

**Comment by pkarman** [comment]
going to create a PR to rollback that column change. The uuid extension is still required however.

Should not need to create a new user to install the extension, but should document sudo of some kind might be necessary.

**Comment by jessieay** [comment]
PR #81 was merged so this issue has been addressed. Closing.
