### ISSUE TITLE
Updates to JSON schema and example

### ISSUE THREAD

**Issue by scottdchristian** [18F/e-manifest#98]
@pkarman 
Here are the updates to the "post-manifest" schema and the "_manifest" JSON files.  Please merge with 90.  I'll figure out how to use GitHub. Thanks for the opportunity to try and help.

A few things of note and questions.  

1) Please check out.  .
2) The manifest schema validates and the example validates, but I may be having issues with arrays and the signature block.  I used http://jsonschemalint.com/ amongst other tools.
3)  Why is the generator section required if we need just the manifest tracking number.
4) @jessieay I renamed the user defined field to handler defined field.

[Manifest-Schema-20160121.zip](https://github.com/18F/e-manifest/files/99805/Manifest-Schema-20160121.zip)

**Comment by pkarman** [comment]
Thanks, Scott.

> 1) Please check out.

Committed in 82acb8d

> 2) The manifest schema validates and the example validates, but I may be having issues with arrays and the signature block. I used http://jsonschemalint.com/ amongst other tools.

One bug I found noted here: https://github.com/18F/e-manifest/blob/swagger-tests/public/schemas/post-manifest.json#L118

the regex pattern does not match the min/max restrictions.

> 3) Why is the generator section required if we need just the manifest tracking number.

generator is the parent attribute as defined in the schema.

**Comment by scottdchristian** [comment]
Thanks, responses in <<>>, below

Scott
On Jan 21, 2016, at 5:13 PM, Peter Karman <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks, Scott.

1) Please check out.

Committed in 82acb8dhttps://github.com/18F/e-manifest/commit/82acb8dccfac820e672a63f4cc9644f8c397e016

<<thanks!>>

2) The manifest schema validates and the example validates, but I may be having issues with arrays and the signature block. I used http://jsonschemalint.com/ amongst other tools.

One bug I found noted here: https://github.com/18F/e-manifest/blob/swagger-tests/public/schemas/post-manifest.json#L118

the regex pattern does not match the min/max restrictions.

<<Copy paste error.  The regex is correct the field has a length of 3 e.g. "G01", "G02">>

3) Why is the generator section required if we need just the manifest tracking number.

generator is the parent attribute as defined in the schema.

<<thanks>>

##

**Comment by scottdchristian** [comment]
One item of note. I/we will need to add a field called density under manifest_item

**Comment by pkarman** [comment]
I have opened https://trello.com/c/DmtDl6pm to refer to the `density` attribute.

Closing this since #90 was merged with schema fixes.
